apiVersion: v1
kind: ConfigMap
metadata:
  name: core-api-config
  namespace: dev
data:
  DB_URL: "jdbc:postgresql://postgres:5432/hanatalk"
  KAFKA_BOOTSTRAP_SERVERS: "kafka:9092"
  OTEL_EXPORTER_OTLP_ENDPOINT: "http://otel-collector:4318/v1/traces"
  OTEL_SAMPLING_PROBABILITY: "1.0"
